test: Use `command -v` instead of `which`
/usr/bin/which is deprecated on Debian unstable:

ERROR:  query: /usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.